COMPONENT=EasyDisseminationAppC
TINYOS_ROOT_DIR?=/Users/osmanodemis/Desktop/wsn/tinyOS/tinyos-main
TOSDIR?=/Users/osmanodemis/Desktop/wsn/tinyOS/tinyos-main/tos
CFLAGS += -I$(TOSDIR)/lib/net
CFLAGS += -I$(TOSDIR)/lib/net/drip
include $(TINYOS_ROOT_DIR)/Makefile.include