COMPONENT=EasyCollectionAppC
TINYOS_ROOT_DIR?=/Users/osmanodemis/Desktop/wsn/tinyOS/tinyos-main
TOSDIR?=/Users/osmanodemis/Desktop/wsn/tinyOS/tinyos-main/tos
CFLAGS += -I$(TOSDIR)/lib/net \
          -I$(TOSDIR)/lib/net/le \
          -I$(TOSDIR)/lib/net/ctp
include $(TINYOS_ROOT_DIR)/Makefile.include